# Generated by Django 5.1.6 on 2025-03-14 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('recorded_datetime', models.DateTimeField(auto_now_add=True)),
                ('procedure_name', models.CharField(max_length=100)),
                ('procedure_notes', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('recorded_datetime', models.DateTimeField(auto_now_add=True)),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('recorded_datetime', models.DateTimeField(auto_now_add=True)),
                ('hemoglobin', models.FloatField()),
                ('white_blood_cells', models.IntegerField()),
                ('platelets', models.IntegerField()),
                ('test_name', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=100)),
                ('lab_report', models.FileField(upload_to='lab_reports/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='rec_app.staffusers')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('recorded_datetime', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(max_length=100)),
                ('scan_result', models.FileField(upload_to='imaging_reports/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('recorded_datetime', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField()),
                ('oxygen_level', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
