# Generated by Django 5.1.6 on 2025-04-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfactor2',
            old_name='immmobilising_plaster_cast',
            new_name='immobilising_plaster_cast',
        ),
    ]
