# Generated by Django 5.1.6 on 2025-03-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Imaging',
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='ServiceProcedure',
        ),
        migrations.DeleteModel(
            name='StaffUsers',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
