# Generated by Django 5.1.6 on 2025-03-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_alter_labresult_doctor_imaging_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Imaging',
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='ServiceProcedure',
        ),
        migrations.DeleteModel(
            name='StaffUsers',
        ),
    ]
