# Generated by Django 5.1.6 on 2025-03-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imaging',
            name='report',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='report',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='report',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='report',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='report',
        ),
    ]
