# Generated by Django 5.1.6 on 2025-03-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rec_app', '0008_remove_labresult_doctor_remove_labresult_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('summary', models.TextField()),
                ('report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure_name', models.CharField(max_length=100)),
                ('procedure_notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('summary', models.TextField()),
                ('report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('summary', models.TextField()),
                ('report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('hemoglobin', models.FloatField()),
                ('white_blood_cells', models.FloatField()),
                ('platelets', models.FloatField()),
                ('test_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('summary', models.TextField()),
                ('report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging', to='rec_app.staffusers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vitals', 'Vitals'), ('lab_results', 'Lab Results'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('services_procedures', 'Services & Procedures')], max_length=50)),
                ('summary', models.TextField()),
                ('report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.CharField(max_length=255)),
                ('recorded_datetime', models.DateTimeField()),
                ('blood_pressure', models.CharField(max_length=50)),
                ('bmi', models.FloatField()),
                ('grbs', models.CharField(max_length=50)),
                ('cvs', models.CharField(max_length=50)),
                ('cns', models.CharField(max_length=50)),
                ('respiratory_rate', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_app.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
