# Generated by Django 5.1.6 on 2025-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_on_services', models.TextField(blank=True, null=True)),
                ('provisional_feedback', models.TextField(blank=True, null=True)),
                ('feedback_plan', models.TextField(blank=True, null=True)),
                ('expected_outcome_of_feedback', models.TextField(blank=True, null=True)),
                ('preventive_feedback_aspects', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_title', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_to_feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('duration_of_experience', models.TextField(blank=True, null=True)),
                ('present_illness', models.TextField(blank=True, null=True)),
                ('past_illness', models.TextField(blank=True, null=True)),
                ('experience_feedback', models.TextField(blank=True, null=True)),
                ('health_feedback', models.TextField(blank=True, null=True)),
                ('hart_feedback', models.TextField(blank=True, null=True)),
                ('stroke_feedback', models.TextField(blank=True, null=True)),
                ('other_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PainAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_intensity', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('location_of_service', models.CharField(max_length=255)),
                ('quality_of_service', models.CharField(choices=[('Constant', 'Constant Feedback'), ('Intermittent', 'Intermittent Feedback')], max_length=50)),
                ('character_of_service', models.JSONField(default=list)),
                ('factors_affecting_rating', models.TextField()),
                ('factors_improving_experience', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Critical', 'Critical'), ('Serious', 'Serious'), ('Moderate', 'Moderate'), ('Mild', 'Mild'), ('Recovered', 'Recovered'), ('Stable', 'Stable'), ('Deteriorating', 'Deteriorating'), ('Improving', 'Improving')], default='Stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_feedback', models.BooleanField(default=False)),
                ('postpartum_feedback', models.BooleanField(default=False)),
                ('condition_feedback', models.BooleanField(default=False)),
                ('contraceptive_feedback', models.BooleanField(default=False)),
                ('age_feedback', models.BooleanField(default=False)),
                ('obesity_feedback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_feedback', models.BooleanField(default=False)),
                ('postpartum_feedback', models.BooleanField(default=False)),
                ('condition_feedback', models.BooleanField(default=False)),
                ('contraceptive_feedback', models.BooleanField(default=False)),
                ('age_feedback', models.BooleanField(default=False)),
                ('obesity_feedback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_feedback', models.BooleanField(default=False)),
                ('surgery_feedback', models.BooleanField(default=False)),
                ('surgical_feedback', models.BooleanField(default=False)),
                ('access_feedback', models.BooleanField(default=False)),
                ('health_condition_feedback', models.BooleanField(default=False)),
                ('feedback_on_condition', models.BooleanField(default=False)),
                ('bedridden_feedback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_feedback', models.BooleanField(default=False)),
                ('heart_failure_feedback', models.BooleanField(default=False)),
                ('resistance_feedback', models.BooleanField(default=False)),
                ('deficiency_feedback', models.BooleanField(default=False)),
                ('health_condition_feedback', models.BooleanField(default=False)),
                ('feedback_on_condition', models.BooleanField(default=False)),
                ('condition_feedback', models.BooleanField(default=False)),
                ('thrombocytopenia_feedback', models.BooleanField(default=False)),
                ('heart_feedback', models.BooleanField(default=False)),
                ('infection_feedback', models.BooleanField(default=False)),
                ('mutation_feedback', models.BooleanField(default=False)),
                ('antibody_feedback', models.BooleanField(default=False)),
                ('disorder_feedback', models.BooleanField(default=False)),
                ('syndrome_feedback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_surgery_feedback', models.BooleanField(default=False)),
                ('fracture_feedback', models.BooleanField(default=False)),
                ('trauma_feedback', models.BooleanField(default=False)),
                ('surgery_feedback', models.BooleanField(default=False)),
                ('stroke_feedback', models.BooleanField(default=False)),
                ('injury_feedback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('hrs_drops_mins', models.CharField(max_length=20)),
                ('dose', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('medicine_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
