# Generated by Django 5.1.6 on 2025-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0012_alter_imaging_patient_alter_labresult_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaging',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceprocedure',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
