# Generated by Django 5.1.6 on 2025-04-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0013_imaging_last_updated_at_labresult_last_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarePlanFeedback',
        ),
        migrations.DeleteModel(
            name='InitialAssessment',
        ),
        migrations.DeleteModel(
            name='NursingNote',
        ),
        migrations.DeleteModel(
            name='PainAssessment',
        ),
        migrations.DeleteModel(
            name='ProgressNote',
        ),
        migrations.DeleteModel(
            name='RiskFactor1',
        ),
        migrations.DeleteModel(
            name='RiskFactor2',
        ),
        migrations.DeleteModel(
            name='RiskFactor3',
        ),
        migrations.DeleteModel(
            name='RiskFactor4',
        ),
        migrations.DeleteModel(
            name='RiskFactor5',
        ),
        migrations.DeleteModel(
            name='TreatmentChart',
        ),
    ]
