# Generated by Django 5.1.4 on 2025-04-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0015_careplanfeedback_initialassessment_nursingnotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresult',
            old_name='test_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='hemoglobin',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='platelets',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='result_value',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='white_blood_cells',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='recorded_datetime',
        ),
        migrations.AlterField(
            model_name='imaging',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='serviceprocedure',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
