# Generated by Django 5.1.6 on 2025-03-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vitals',
        ),
    ]
