# Generated by Django 5.1.6 on 2025-03-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_history_remove_patient_prescription_and_more'),
        ('rec_app', '0011_alter_prescription_patient_alter_vitals_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec_app.progressnote'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='rec_app.prescription'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_vitals_ref', to='rec_app.vitals'),
        ),
    ]
