# Generated by Django 5.1.6 on 2025-03-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_history_patient_prescription_patient_vitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vitals',
        ),
    ]
