# Generated by Django 5.1.7 on 2025-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_history_remove_patient_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
